import Image from "next/image";
import styles from "./page.module.css";
import Head from "next/head";
import {GET} from "./sheets/route";
import { NextRequest } from "next/server";

export default async function Home() {
    return (
        <>
            <Head>
                <title>Stree Shakti Prabodhan</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.heroSection}>
                <div className={styles.navContainer}>
                    <h3>Logo</h3>
                    <div className={styles.navLinks}>
                        <div className={styles.navLink}>Link</div>
                        <div className={styles.navLink}>Link</div>
                        <div className={styles.navLink}>Link</div>
                        <div className={styles.navLink}>Link</div>
                    </div>
                </div>
                <div className={styles.heroContent}>
                    <h3 className={styles.heroItem}>Jnana Prabodhini</h3>
                    <h1 className={styles.heroItem}>Stree Shakti Prabodhan</h1>
                    <h4 className={styles.heroItem}>Empowering women, one story at a time.</h4>
                </div>
            </section>
            <section className={styles.itemSection}>
                <div>
                    <h1>Featured</h1>
                </div>
            </section>
        </>
    );
}