import Image from "next/image";
import styles from "./page.module.css";
import Head from "next/head";
import Card from "./_card";

interface ItemData {
    ProductNum: string;
    Image: string;
    AltText: string;
    Name: string;
    Description: string;
    Price: number;
    Dimensions: string;
    Availability: string;
    Category: string;
    Quantity: number;
}

export default async function Home() {
    const data = await fetch("https://stree-shakti-prabodhini.vercel.app/sheets", { next: { revalidate: 60 } }).then(
        async (val) => {
            return (await val.json()) as ItemData[];
        }
    );

    return (
        <>
            <Head>
                <title>Stree Shakti Prabodhan</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.heroSection}>
                <div className={styles.navContainer}>
                    <h3>Logo</h3>
                    <div className={styles.navLinks}>
                        <div className={styles.navLink}>Link</div>
                        <div className={styles.navLink}>Link</div>
                        <div className={styles.navLink}>Link</div>
                        <div className={styles.navLink}>Link</div>
                    </div>
                </div>
                <div className={styles.heroContent}>
                    <h2 className={styles.heroItem}>Jnana Prabodhini</h2>
                    <h1 className={styles.heroItem}>Stree Shakti Prabodhan</h1>
                    <h4 className={styles.heroItem}>Empowering women, one story at a time.</h4>
                </div>
            </section>
            <section className={styles.itemSection}>
                <div className={styles.itemGroups}>
                    <div>
                        <h1>Note</h1>
                        <p>For bulk orders (more than 10 items of one kind) or items that are unavailable please contact Jnana Prabodhini directly.</p>
                    </div>
                    {Array.from(new Set(data.map((item) => item.Category))).map((val, index) => {
                        return (
                            <div key={val}>
                                <h1>{val}</h1>
                                <div className={styles.itemGroup}>
                                    {data
                                        .filter((point) => point.Category == val)
                                        .map((item) => {
                                            return Card(item);
                                        })}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </section>
        </>
    );
}
